apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environment-promotion
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: prod
          - namespace: staging
          - namespace: qa
  template:
    metadata:
      name: '{{ namespace }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/by-nelson/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: './environment-promotion/envs/{{ namespace }}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
